#!/bin/bash

echo "$TRAVIS_BRANCH"

if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" != "true" ]
then
  echo "Deploying!" &&
  cp CNAME dist
  cd dist &&
  git config --global user.email "travis@bq.com"
  git config --global user.name "TRAVIS-CI"
  git init &&
  git add . &&
  git commit -m "deploy" &&
  git push --force --quiet "https://${GH_OAUTH_TOKEN}@github.com/bquarks/polymer-element-catalog" master:gh-pages > /dev/null 2>&1
fi
